# Generated by Django 5.0.6 on 2024-06-12 17:15

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=200)),
                ('host_initials', models.CharField(max_length=3)),
                ('property_title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique_for_date='created_at')),
                ('property_type', models.CharField(max_length=200)),
                ('property_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bedroom_no', models.CharField(max_length=200)),
                ('bathroom_no', models.CharField(max_length=200)),
                ('property_location', models.CharField(max_length=200)),
                ('property_description', models.TextField()),
                ('contact_info', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to=api.models.upload_to, verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.post')),
            ],
        ),
    ]
